replicaCount: 1
image:
  repository: 386235758526.dkr.ecr.us-east-1.amazonaws.com/vmware-hw-monitor-app
  pullPolicy: Always
  tag: "0.1.3"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  annotations:
    prometheus.io/port: '9877'
    prometheus.io/scrape: 'true'
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/issuer: cloudflare-minube-cr
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
  hosts:
    - host: vmware-hw-monitor-app.minube.cr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: vmware-hw-monitor-app-minube-cr-tls
      hosts:
        - vmware-hw-monitor-app.minube.cr
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
