apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmware-hw-monitor-app
  namespace: argocd
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/vmware-hw-monitor-app
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/vmware-hw-monitor-app
    repoURL: https://github.com/enzojimenez/vmware-hw-monitor-app.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m0s
      limit: 2