apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vmware-hw-monitor-app.fullname" . }}
  labels:
    {{- include "vmware-hw-monitor-app.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "sleep": 10,
      "urls": [
        "https://httpstat.us/200",
        "https://httpstat.us/503"
      ],
      "metrics": [
        {
          "name": "sample_external_url_up",
          "help": "Is UP and responding 200 OK?"
        },
        {
          "name": "sample_external_url_response_ms",
          "help": "Response in Milliseconds"
        }
      ]
    }